import type { Photo } from "@/models/Images";
import Image from "next/image";
import Link from "next/link";

type Props = { //* here we define the type of props that we expect to receive
    photo: Photo
}

export default function ImgContainer({ photo }: Props ){
    const widthHeightRatio = photo.height / photo.width;
    const galleryHigh = Math.ceil(250 * widthHeightRatio)
    const photoSpans = Math.ceil(galleryHigh /10) +1;

    return(
        <div className="w-[250px] justify-self-center"
            style={{gridRow: `span ${photoSpans}`}}
        >
            <Link href={photo.url} target="_blank" className="grid place-content-center">
                <div className="rounded-2xl overflow-hidden group">
                    <Image 
                        src={photo.src.large}
                        alt={photo.alt}
                        width={250}
                        height={galleryHigh}
                        sizes="250px"
                        placeholder="blur"
                        blurDataURL={photo.blurredDataUrl}
                        className="overflow-hidden group-hover:opacity-75 cursor-pointer"
                        />
                </div>
            </Link>
        </div>
    )
}

//* the sizes are generated by RespImageLint
//* a tool that analyzes the images in a site and provides the best sizes for each breakpoint
//? width and height are required, unless we use the fill property