import type { Photo } from "@/models/Images";
import Image from "next/image";

type Props = { //* here we define the type of props that we expect to receive
    photo: Photo
}

export default function ImgContainer({ photo }: Props ){
    return(
        <div className="h-64 bg-gray-200 rounded-2xl relative group">
            <Image 
                src={photo.src.large}
                alt={photo.alt}
                fill={true}
                sizes="(min-width: 1280px) 278px, (min-width: 1040px) calc(12.73vw + 118px), (min-width: 800px) 33.18vw, (min-width: 540px) 50vw, calc(100vw - 16px)"
                placeholder="blur"
                blurDataURL={photo.blurredDataUrl}
                className="object-cover overflow-hidden group-hover:opacity-75 cursor-pointer"
            />
        </div>
    )
}

//* the sizes are generated by RespImageLint
//* a tool that analyzes the images in a site and provides the best sizes for each breakpoint
//? width and height are required, unless we use the fill property